Repository Lambda-School-Labs/trashpanda-fe, pull requests merged in 2020-02, with the labels that each got.

#16 Add code climate badges
  README.md
Labels: documentation

#22 Feature/#21
  public/index.html
  src/App.css
  src/App.js
  src/atoms/Spinner.jsx
  src/images/arrow_back.svg
  src/images/camera.svg
  src/images/compost.svg
  src/images/home.svg
  src/images/landfill.svg
  src/images/loading.svg
  src/images/offsite.svg
  src/images/recycle.svg
  src/images/walking_graphic.svg
  src/index.css
  src/molecules/Badge.jsx
  src/molecules/BottomNav.jsx
  src/molecules/LocationCard.jsx
  src/molecules/MaterialsDisplay.jsx
  src/molecules/NavBar.jsx
  src/molecules/ZipSearchBar.jsx
  src/organisms/CategoryPage.jsx
  src/organisms/LocationsPage.jsx
  src/organisms/MaterialPage.jsx
Labels: feature

#24 Feature/#20
  src/molecules/CategoryGrid.jsx
  src/molecules/GridCard.jsx
  src/molecules/ZipSearchBar.jsx
  src/organisms/CategoryPage.jsx
  src/organisms/HomePage.jsx
  src/organisms/LocationsPage.jsx
  src/organisms/MaterialPage.jsx
Labels: feature

#25 Feature/#19
  src/images/lens_dark.svg
  src/molecules/CategoryGrid.jsx
  src/molecules/HomeIntro.jsx
  src/molecules/HomeSearchBar.jsx
  src/organisms/HomePage.jsx
Labels: feature

#29 Feature/#17
  public/index.html
  src/App.js
  src/atoms/Button.jsx
  src/images/batteries.jpg
  src/images/landfill_filled.svg
  src/images/man_trash.svg
  src/images/raccoon.svg
  src/images/recycle_filled.svg
  src/images/trashpanda.svg
  src/organisms/HomePage.jsx
  src/organisms/LandingPage.jsx
  src/organisms/PermissionPage.jsx
Labels: feature

#32 Remove CRA and babel
  .babelrc
  package-lock.json
  package.json
  public/index.html
Labels: bug

#33 Feature/23
  .babelrc
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/organisms/LocationsPage.jsx
  src/organisms/MaterialPage.jsx
  src/organisms/__tests__/MaterialPage.test.js
  svgTransform.js
Labels: feature

#30 Feature/8
  src/molecules/HomeSearchBar.jsx
Labels: feature

#36 Update Read Me
  README.md
Labels: documentation

#38 Feature/34
  .babelrc
  .gitignore
  package-lock.json
  package.json
  src/organisms/__tests__/MaterialPage.test.js
Labels: bug, feature

#37 Feature/28 cache
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/molecules/HomeSearchBar.jsx
  src/organisms/LocationsPage.jsx
  src/organisms/MaterialPage.jsx
Labels: feature

#39 Add type maps for postalcode and location data
  src/index.js
Labels: bug

#40 Feature/26
  src/organisms/__tests__/CategoryPage.test.js
  src/organisms/__tests__/MaterialPage.test.js
  src/organisms/__tests__/mock_data/mockOrganismState.js
Labels: feature

#41 Feature/#14
  package-lock.json
  package.json
  src/App.js
  src/atoms/Button.jsx
  src/molecules/Badge.jsx
  src/molecules/BottomNav.jsx
  src/molecules/GridCard.jsx
  src/organisms/LocationsPage.jsx
Labels: feature

#42 Feature/26
  src/organisms/__tests__/CategoryPage.test.js
  src/organisms/__tests__/MaterialPage.test.js
  src/organisms/__tests__/mock_data/mockOrganismState.js
Labels: enhancement

#48 adds code climate yml file to ignore tests in maintainability score
  .codeclimate.yml
Labels: enhancement

#50 Feature/27
  src/organisms/__tests__/HomePage.test.js
  src/organisms/__tests__/MaterialPage.test.js
  src/organisms/__tests__/mock_data/mockQueries.js
Labels: feature

#51 Feature 43
  src/organisms/__tests__/LandingPage.test.js
Labels: feature

#64 Adding google analytics script tag in head
  public/index.html
Labels: feature

#59 Add code climate test coverage
  .github/workflows/ci.yml
  package.json
Labels: documentation

#49 Add local persistent cache
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/AppCache.js
  src/index.js
  src/molecules/CategoryGrid.jsx
  src/organisms/CategoryPage.jsx
  src/organisms/HomePage.jsx
  src/organisms/LocationsPage.jsx
  src/organisms/MaterialPage.jsx
  src/organisms/PermissionPage.jsx
  src/resolvers.js
  src/utils/UserLocation.js
Labels: feature

#80 Feature/66
  src/App.js
  src/images/darkmode.svg
  src/images/lightmode.svg
  src/molecules/Badge.jsx
  src/molecules/BottomNav.jsx
  src/molecules/GridCard.jsx
  src/molecules/HomeSearchBar.jsx
  src/molecules/LocationCard.jsx
  src/molecules/ToggleTheme.jsx
  src/molecules/ZipSearchBar.jsx
  src/molecules/global.jsx
  src/molecules/theme.js
  src/molecules/useDarkMode.jsx
  src/organisms/CategoryPage.jsx
  src/organisms/HomePage.jsx
  src/organisms/LocationsPage.jsx
  src/organisms/MaterialPage.jsx
Labels: feature

#53 Feature 44
  src/organisms/__tests__/LocationsPage.test.js
  src/organisms/__tests__/mock_data/mockOrganismState.js
Labels: feature

#52 Feature 45
  src/organisms/__tests__/PermissionPage.test.js
  src/organisms/__tests__/mock_data/mockStateFunctions.js
Labels: feature

#81 Bug/79 first load
  src/App.js
  src/AppCache.js
  src/molecules/CategoryGrid.jsx
Labels: bug

#77 Add favicons and update manifest
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/manifest.webmanifest
  public/mstile-150x150.png
Labels: feature

#83 Feature/62
  src/App.js
  src/molecules/BottomNav.jsx
  src/organisms/CameraPage.js
  src/organisms/__tests__/MaterialPage.test.js
  src/organisms/hooks/CameraAsyncHook.js
Labels: feature

#87 Feature/#63
  src/App.js
  src/atoms/Button.jsx
  src/atoms/StepCircle.jsx
  src/images/location_illustration.svg
  src/images/photo_illustration.svg
  src/images/trash_man.svg
  src/images/trash_man_dark.svg
  src/molecules/CategoryGrid.jsx
  src/molecules/Stepper.jsx
  src/molecules/theme.js
  src/organisms/CategoryPage.jsx
  src/organisms/LandingPage.jsx
  src/organisms/LocationsPage.jsx
  src/organisms/PermissionPage.jsx
  src/organisms/TutorialPage.jsx
  src/organisms/__tests__/LandingPage.test.js
  src/organisms/__tests__/PermissionPage.test.js
  src/organisms/__tests__/TutorialPage.test.js
  src/utils/UserLocation.js
Labels: feature

#89 Feature/74
  src/images/back_arrow_lite.svg
  src/images/camera_center_icon.svg
  src/images/camera_icon_camera.svg
  src/images/camera_pg_button_dark.svg
  src/images/camera_pg_button_lite.svg
  src/images/home_icon_camera_dark.svg
  src/images/home_icon_lite.svg
  src/images/search_icon.svg
  src/images/search_icon_camera_dark.svg
  src/molecules/BottomNav.jsx
  src/molecules/theme.js
Labels: feature

#88 Feature/65 pwa
  package-lock.json
  package.json
  parcelBundler.js
  public/index.html
  public/sw.js
  src/App.js
  src/images/arrow_back.svg
  src/images/camera.svg
  src/images/category_placeholder.svg
  src/images/compost.svg
  src/images/darkmode.svg
  src/images/home.svg
  src/images/landfill.svg
  src/images/lens.svg
  src/images/lens_dark.svg
  src/images/lightmode.svg
  src/images/loading.svg
  src/images/man_trash.svg
  src/images/offsite.svg
  src/images/raccoon.svg
  src/images/recycle.svg
  src/images/walking_graphic.svg
  src/index.js
  src/organisms/PermissionPage.jsx
  src/resolvers.js
  src/serviceWorker.js
  workboxBuild.js
Labels: feature

#94 Feature/84
  src/App.js
  src/images/chevrons_up_dark.svg
  src/images/chevrons_up_lite.svg
  src/images/results_button.svg
  src/molecules/ResultsTab.jsx
  src/molecules/useDarkMode.jsx
  src/organisms/CameraPage.js
Labels: feature

#99 Double click on "Go" issue
  src/organisms/LocationsPage.jsx
Labels: bug

#100 Feature/98
  public/index.html
  public/sw.js
  src/organisms/LocationsPage.jsx
Labels: bug

#103 Update cache on reload
  package.json
  src/App.js
  src/organisms/CategoryPage.jsx
Labels: bug

#105 Added redirects file for netlify issue bug
  package-lock.json
  package.json
  parcelBundler.js
  public/_redirects
Labels: bug

#110 Fixes the search bar and dark mode icon to align with category icons
  package-lock.json
  package.json
  src/molecules/HomeSearchBar.jsx
  src/molecules/ToggleTheme.jsx
  src/organisms/HomePage.jsx
Labels: bug

#111 moved home button in nav for mobile widths
  src/molecules/BottomNav.jsx
Labels: bug

#114 Feature/73
  src/organisms/LocationsPage.jsx
Labels: bug

#116 Remove apollo persist
  src/App.js
  src/AppCache.js
  src/organisms/LocationsPage.jsx
  src/organisms/TutorialPage.jsx
  src/utils/UserLocation.js
Labels: bug

#117 Feature/92 camera warp
  package-lock.json
  package.json
  src/organisms/CameraPage.js
Labels: bug

#119 Feature/104
  src/App.js
  src/images/CameraButtonAttempt2.svg
  src/images/camera_icon_camera_light.svg
  src/images/home_icon_camera_dark.svg
  src/images/home_icon_camera_lite.svg
  src/images/search_icon_camera_dark.svg
  src/images/search_icon_camera_lite.svg
  src/molecules/BottomNav.jsx
  src/molecules/CameraNav.jsx
Labels: feature

#120 Feature/70
  src/App.js
  src/molecules/ClusterResult.jsx
  src/molecules/ResultsTab.jsx
  src/organisms/CameraPage.js
Labels: feature

#123 Feature/#122
  src/molecules/theme.js
  src/organisms/LocationsPage.jsx
Labels: feature

#124 Feature/121
  src/App.js
  src/molecules/CameraNav.jsx
  src/molecules/HomeSearchBar.jsx
  src/organisms/HomePage.jsx
Labels: feature

#131 testing tutorial page Next button
  src/organisms/__tests__/TutorialPage.test.js
Labels: enhancement

#129 Stop camera when page unmounts
  src/organisms/CameraPage.js
Labels: bug

#127 Feature/125 cluster page
  src/App.js
  src/molecules/ClusterResult.jsx
  src/organisms/CameraPage.js
  src/organisms/ClusterPage.jsx
Labels: feature

#139 Replaced placeholder image with new one
  src/images/category_placeholder.png
  src/images/category_placeholder.svg
  src/molecules/CategoryGrid.jsx
  src/organisms/CategoryPage.jsx
Labels: feature

#141 no results search button autofocuses on search when return to main
  src/App.js
  src/molecules/ClusterResult.jsx
  src/organisms/CameraPage.js
Labels: feature

#146 Fix camera not unloading when leaving page
  src/organisms/CameraPage.jsx
  src/organisms/ClusterPage.jsx
Labels: bug

#140 added logic to LocationPage handleClick to handle invalid postal code…
  src/organisms/LocationsPage.jsx
Labels: bug

#156 Bug/154
  src/molecules/HomeSearchBar.jsx
Labels: bug

#157 Feature/144
  package.json
  src/organisms/__tests__/HomePage.test.js
  src/organisms/__tests__/mock_data/mockOrganismState.js
Labels: bug

#155 Feature/#151
  src/atoms/Spinner.jsx
  src/organisms/LocationsPage.jsx
Labels: feature

#164 Fixed next button positioning by setting fixed heights to titles/texts
  src/organisms/TutorialPage.jsx
Labels: bug

#158 Feature/153 camera nav
  package-lock.json
  package.json
  src/App.css
  src/molecules/CameraNav.jsx
  src/molecules/ClusterResult.jsx
  src/organisms/CameraPage.jsx
Labels: feature

#162 Hide nav if search is focused
  src/App.js
  src/molecules/BottomNav.jsx
  src/molecules/HomeSearchBar.jsx
  src/organisms/HomePage.jsx
Labels: feature

#165 Set width and height of button
  src/molecules/BottomNav.jsx
Labels: bug

#166 Feature/143
  src/App.js
  src/organisms/CategoryPage.jsx
  src/organisms/__tests__/CategoryPage.test.js
  src/organisms/__tests__/MaterialPage.test.js
  src/organisms/__tests__/mock_data/mockOrganismState.js
Labels: bug

#169 Feature/142
  src/molecules/__mocks__/Badge.jsx
  src/organisms/MaterialPage.jsx
  src/organisms/__tests__/MaterialPage.test.js
Labels: bug

#176 Change opacity of categorylist when search is focused
  src/molecules/CategoryGrid.jsx
  src/organisms/HomePage.jsx
Labels: feature

#181 Feature/174 search border
  .gitattributes
  src/images/lens.svg
  src/images/lens_dark.svg
  src/images/search_icon.svg
  src/images/search_icon_camera_dark.svg
  src/images/search_icon_camera_lite.svg
  src/molecules/BottomNav.jsx
  src/molecules/CameraNav.jsx
  src/molecules/HomeSearchBar.jsx
  src/molecules/ZipSearchBar.jsx
  src/molecules/__mocks__/Badge.jsx
  src/molecules/theme.js
  src/organisms/LocationsPage.jsx
  src/organisms/MaterialPage.jsx
  src/organisms/__tests__/CategoryPage.test.js
  src/organisms/__tests__/HomePage.test.js
  src/organisms/__tests__/mock_data/mockOrganismState.js
  src/utils/inputFocused.js
Labels: feature

#180 cleans up the read me file with accurate data
  README.md
Labels: documentation

#182 Re-positioned Blurb and search bar on LocationsPage
  src/organisms/LocationsPage.jsx
Labels: feature

#178 Feature/#167
  src/App.js
  src/SubCategoryData.js
  src/atoms/Plastic.jsx
  src/molecules/GridCard.jsx
  src/molecules/theme.js
  src/organisms/CategoryPage.jsx
  src/organisms/SubCategoryPage.jsx
Labels: feature
