Repository Lambda-School-Labs/trashpanda-fe, pull requests merged in 2020-03, with the labels that each got.

#184 Update radius to 5px
  src/atoms/Button.jsx
  src/atoms/StepCircle.jsx
  src/molecules/ClusterResult.jsx
  src/molecules/HomeSearchBar.jsx
  src/molecules/ZipSearchBar.jsx
  src/organisms/MaterialPage.jsx
Labels: enhancement

#183 Darken border slightly in dark mode
  src/molecules/theme.js
Labels: enhancement

#185 Feature/172 move nav
  src/App.css
  src/App.js
  src/atoms/Spinner.jsx
  src/images/arrow_back.svg
  src/images/back_arrow_lite.svg
  src/images/home_icon_camera_lite.svg
  src/images/home_icon_lite.svg
  src/molecules/BottomNav.jsx
  src/molecules/CameraNav.jsx
  src/molecules/CategoryGrid.jsx
  src/molecules/ClusterResult.jsx
  src/molecules/HomeSearchBar.jsx
  src/molecules/TakeAPhoto.jsx
  src/molecules/ToggleTheme.jsx
  src/molecules/TopNav.jsx
  src/organisms/CameraPage.jsx
  src/organisms/CategoryPage.jsx
  src/organisms/ClusterPage.jsx
  src/organisms/HomePage.jsx
  src/organisms/MaterialPage.jsx
  src/organisms/SubCategoryPage.jsx
Labels: enhancement

#187 Fix margin on h2
  src/organisms/SubCategoryPage.jsx
Labels: bug

#189 Add spinner while clusterdata is loading
  src/organisms/CameraPage.jsx
Labels: feature

#192 Redirect to material if single material found
  src/molecules/ClusterResult.jsx
  src/organisms/CameraPage.jsx
Labels: enhancement

#196 Build Android APK
  android/.gitignore
  android/android.keystore
  android/app-release-signed.apk
  android/app-release-unsigned-aligned.apk
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-hdpi/splash.png
  android/app/src/main/res/drawable-mdpi/splash.png
  android/app/src/main/res/drawable-xhdpi/splash.png
  android/app/src/main/res/drawable-xxhdpi/splash.png
  android/app/src/main/res/drawable-xxxhdpi/splash.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/raw/web_app_manifest.json
  android/app/src/main/res/values/styles.xml
  android/app/src/main/res/xml/filepaths.xml
  android/app/src/main/res/xml/shortcuts.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/package-lock.json
  android/package.json
  android/settings.gradle
  android/store_icon.png
  android/twa-manifest.json
  public/.well-known/assetlinks.json
Labels: feature

#197 Update sha256
  public/.well-known/assetlinks.json
Labels: bug

#198 No results error
  src/molecules/ClusterResult.jsx
  src/molecules/LocationCard.jsx
  src/organisms/ClusterPage.jsx
Labels: bug

#199 Add radius to dashed border
  src/molecules/TakeAPhoto.jsx
Labels: bug

#200 Anchor shutterbutton to bottom center of screen
  src/organisms/CameraPage.jsx
Labels: bug

#201 Fix camera icon colors
  src/molecules/TopNav.jsx
Labels: bug

#204 Update README.md
  README.md
Labels: documentation

#203 Fix nav colors
  src/molecules/TopNav.jsx
Labels: bug

#206 Feature/#205
  public/index.html
  src/App.css
  src/App.js
  src/images/carlo_lucido.png
  src/images/colin_bazzano.png
  src/images/google-play-badge.png
  src/images/jt_kernan.png
  src/images/kendra_mckernan.png
  src/images/lynn_baxter.png
  src/images/mark_artishuk.png
  src/images/mark_halls.png
  src/images/splash_image.svg
  src/images/timothy_hsu.png
  src/images/tobias_reaper.png
  src/images/trevor_clack.png
  src/images/vera_mendes.png
  src/molecules/SplashMainContent.jsx
  src/molecules/SplashNav.jsx
  src/molecules/SplashTeam.jsx
  src/molecules/SplashTeamCard.jsx
  src/organisms/SplashPage.jsx
Labels: feature

#208 Changed carlo's image
  src/images/carlo_lucido.png
Labels: feature

#210 Dark mode bug removed from splash page
  src/App.js
  src/molecules/global.jsx
Labels: feature

#212 Setup fullstory analytics
  public/index.html
Labels: feature

#236 Update apk readme
  android/package.json
  android/readme.md
Labels: documentation
